# 下载每个页面后 sleep 时间
PAGE_DL_SHORT_SLEEP = 0.5
PAGE_DL_NORMAL_SLEEP = 0.8
PAGE_DL_LONG_SLEEP = 1.2
# 下载每个文件后 sleep 时间
FILE_DL_SHORT_SLEEP = 0.5
FILE_DL_NORMAL_SLEEP = 0.8
FILE_DL_LONG_SLEEP = 1.2

# 下载重试次数
DOWNLOAD_TRIES = 5
# 队列拥挤评定阈值，对生产者消费者提速或降速
QUEUE_CROWDED_SIZE = 500

FILE_LOG = True
CONSOLE_LOG = True
LOG_FILENAME = 'spider.log'
